### PR TITLE
moved js libs to cdn, linted html and js files

### PR DESCRIPTION
**Pull request by OmgImAlexis**
I've changed the js libraries to use the copy from cdnjs, linted the HTML and Javascript files and left a few notes in the Javascript so you can fix things my linter picked up. :+1:

### CODE REVIEW

**Comment by asakurasol** [comment]
@OmgImAlexis This is awesome! Thanks!

**Comment by asakurasol** [comment]
Hmmm the game breaks for some reason from the PR. I will investigate later.

**Comment by OmgImAlexis** [comment]
I found the issue, since you didn't include a `bower.json` file I didn't exactly know which packages you were using and replaced the drag and drop library with the wrong one. I'll push a fix to my fork in a sec.

**Comment by OmgImAlexis** [comment]
I also noticed that switching from a bunch of if statements in the `Game.prototype.updateNextTo` function causes `window` to be added to the array which shouldn't happen.

**Comment by OmgImAlexis** [comment]
If you could explain what this weird bit of code does I can push a fix.

Since I updated a bunch of the libraries this line now breaks everything. :-1: 

```
$scope.dropFunctions[i] = new Function('ele', "var i = " + i + "; globalListener.setValue(i, ele);");
```

**Comment by asakurasol** [comment]
I apologize, reading the code now it's definitely quite the mess.

I think that line is for creating callback functions associated with the drag-n-drop library I was using at the time. The function is used in the view1.html file 

`drop = "dropFunctions.{{cell.number}}">`

**Comment by OmgImAlexis** [comment]
Could you not just create a single function instead of calling a new anonymous function for every single cell?

**Comment by asakurasol** [comment]
You most definitely can, but it's pretty clear I had no idea what I was doing back then.

**Comment by OmgImAlexis** [comment]
I "think" I fixed it by just changing it to this and then replacing the line you mentioned with `drop="dropFunction({{cell.number}})">`
Since the code is really all over the place I'm not too sure if that's right though but the page does seem to work fine now.

```
$scope.dropFunction = function(cellNumber){
        $scope.globalListener.setValue(cellNumber, angular.element(this));
    };
```

**Comment by asakurasol** [comment]
To check to see if that functionality is still working correctly try drag and drop the number tiles on the sudoku side to the tiles.

Alternatively you can submit the PR and I'll test it.

Thanks for the hardwork!

**Comment by OmgImAlexis** [comment]
You may have to create the PR, the amount of lines changed is causing my Chrome to hang. :disappointed:

**Comment by asakurasol** [comment]
Haha alright. I will work on it when I get home tonight and let you know tomorrow.

**Comment by asakurasol** [comment]
Refactored it and looks like it's working. Go ahead and submit your PR.

**Pull request merged**
